# Generated by Django 3.2.9 on 2022-11-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_chat_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
