# Generated by Django 3.2.9 on 2022-11-16 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='img',
        ),
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.friend'),
        ),
    ]
