# Generated by Django 3.2.9 on 2022-11-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20221116_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.friend'),
        ),
    ]
